# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               SpineML
tagline:             'The Spiking Neural Mark-up Language'
description:         'A website for the Spiking Neural Mark-up Language (SpineML) and the SpineCreator cross platform graphical editor.'
url:                 http://spineml.github.io
baseurl:             ''

# About/contact
author:
  name:              University of Sheffield

# Custom vars
version:             1.0.0

markdown: kramdown
kramdown:
  input: GFM
